  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend
version: '3.8'

x-service-templates:
  app-base: &app-base
    build: .
    volumes:
      - ./:/app
    networks:
      - backend
      - payment-db
      - payment-processor
    depends_on:
      - db
services:
  backend1:
    <<: *app-base
    environment:
      APP_INSTANCE: "backend1"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/backend"
      PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
  backend2:
    <<: *app-base
    environment:
      APP_INSTANCE: "backend2"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/backend"
      PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
  nginx:
    image: nginx:1.25
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
      - payment-processor
    depends_on:
      - backend1
      - backend2
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - payment-db
volumes:
  pgdata:

networks:
  backend:
    driver: bridge
  payment-db:
    driver: bridge
  payment-processor:
    external: true
